
project_id = "hvxevtqyqyvhdzudltya"

[functions.pdf-merge]
verify_jwt = false

[functions.pdf-compress]
verify_jwt = false

[functions.pdf-split]
verify_jwt = false

[functions.pdf-watermark]
verify_jwt = false

[functions.pdf-rotate]
verify_jwt = false

[functions.pdf-protect]
verify_jwt = false

[functions.pdf-unlock]
verify_jwt = false

[functions.pdf-convert-to]
verify_jwt = false

[functions.pdf-convert-from]
verify_jwt = false

[storage.pdfs]
public = true
