// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvxevtqyqyvhdzudltya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2eGV2dHF5cXl2aGR6dWRsdHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzEwMzcsImV4cCI6MjA2MDY0NzAzN30.v1hm5uMbMFqCogENXFBAHm01UzBD8MI7YIvBMHQm4ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);